title: GridOS
description: A framework for developing Bespoke Business Operating Systems
remote_theme: just-the-docs/just-the-docs

url: https://potsed.github.io/GridOS

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
