title: GridOS
description: A framework for developing Bespoke Business Operating Systems
remote_theme: just-the-docs/just-the-docs

url: https://potsed.github.io/GridOS

# baseurl: "/GridOS" # the subpath of your site, e.g. /blog
repository: potsed/GridOS # for github-metadata

# permalink: pretty

# exclude:
#  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
#    - .sass-cache/
#    - .jekyll-cache/
#    - gemfiles/
#    - Gemfile
#    - Gemfile.lock
#    - node_modules/
#    - vendor/bundle/
#    - vendor/cache/
#    - vendor/gems/
#    - vendor/ruby/
#  # specific to the theme website:
#    - bin/
#    - lib/
#    - "*.gemspec"
#    - "*.gem"
#    - LICENSE.txt
#    - package.json
#    - package-lock.json
#    - Rakefile
#    - README.md
#    - CODE_OF_CONDUCT.md
#    - docker-compose.yml
#    - Dockerfile
#  # theme test code
#    - fixtures/

aux_links:
  View on Github: https://github.com/potsed/GridOS

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/GridOS.svg"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.4"

callouts:
  warning:
    title: Take care
    color: red

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\"><img alt=\"Creative Commons Licence\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-sa/4.0/88x31.png\" /></a><br /><span xmlns:dct=\"http://purl.org/dc/terms/\" property=\"dct:title\">GridOS - A Mindset Adoption Framework</span> by <a xmlns:cc=\"http://creativecommons.org/ns#\" href=\"https://grids.consulting\" property=\"cc:attributionName\" rel=\"cc:attributionURL\">Daniel Smith</a> is licensed under a <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\">Creative Commons Attribution-ShareAlike 4.0 International License</a>.<br />Based on a work at <a xmlns:dct=\"http://purl.org/dc/terms/\" href=\"https://potsed.github.io/GridOS/\" rel=\"dct:source\">https://potsed.github.io/GridOS/</a>."

# Footer last edited timestamp
last_edit_timestamp: false # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/potsed/GridOS" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

constants:
  CHANGE_MODEL: Change Effectiveness Model