title: GridOS - 
description: A framework for developing Bespoke Business Operating Systems
theme: just-the-docs
license: MIT
url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
